import Head from "next/head";
import { HouseHold } from "@/components/household";
import { IHouseHoldMember } from "@/components/household/types";

type HomeProps = {
	householdMembers: IHouseHoldMember[];
};

export default function Home({ householdMembers }: HomeProps) {
	return (
		<>
			<Head>
				<title>Neem Household</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<section className="min-w-[500px] w-1/2 mx-auto">
					<HouseHold householdMembers={householdMembers} />
				</section>
			</main>
		</>
	);
}

export async function getServerSideProps() {
	return {
		props: {
			householdMembers: [
				{
					firstName: "Jerome",
					lastName: "Bell",
					preferredName: "Jerome",
					isCovered: true,
					isSubscriber: true,
					type: "PRIMARY",
					ID: "",
				},
				{
					firstName: "StacyASSASASDSSDSDSDSDSDSDSDSDSDSDSDS",
					lastName: "BellSDSDSDSDSSSDSDSDSDSDSDSDSDSDSDSDSDS",
					preferredName: "Stacy",
					isCovered: true,
					isSubscriber: false,
					type: "PRIMARY",
					ID: "",
				},
				{
					firstName: "Rebecca",
					lastName: "Bell",
					preferredName: "Rebecca",
					isCovered: false,
					isSubscriber: false,
					type: "PRIMARY",
					ID: "",
				},
			],
		},
	};
}
